[package]
name = "ansi_colour"
description = "Representation of ansi colours"
version = "0.2.1"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
homepage = "https://github.com/stevebob/ansi-colour"
repository = "https://github.com/stevebob/ansi-colour.git"
documentation = "https://docs.rs/ansi_colour"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
