[package]
name = "terminal_colour"
description = "Representation of terminal colours"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
homepage = "https://github.com/stevebob/terminal_colours.git"
repository = "https://github.com/stevebob/terminal_colours.git"
documentation = "https://docs.rs/terminal_colours"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
